export const CHAT_APPS_ADD_CHAT = "CHAT_APPS_ADD_CHAT";
export const CHAT_APPS_DELETE_CHAT = "CHAT_APPS_DELETE_CHAT";
export const CHAT_APPS_UPDATE_CHAT = "CHAT_APPS_UPDATE_CHAT";
export const CHAT_APPS_RESET = "CHAT_APPS_RESET";
export const CHAT_APPS_TOGGLE_NEW_REPLY_PROFILE = "CHAT_APPS_TOGGLE_NEW_REPLY_PROFILE";

// application
export const PREVIEW_IMAGE = "PREVIEW_IMAGE";
export const CHANGE_MOBILE_HEAD_COLOR = "CHANGE_MOBILE_HEAD_COLOR";
